### ISSUE TITLE
bug: switching from all time to current then going to next page

### ISSUE THREAD

**Issue by Lazylllama** [Cyteon/doubloon-leaderboard#1]
Switching from all time to current or vice versa will break the other pages of the list.

**Comment by Lazylllama** [comment]
[image](https://github.com/user-attachments/assets/276fb329-4339-4bca-90d9-36771b6053a8)

**Comment by cyteon** [comment]
Fixing tmrw

**Comment by cyteon** [comment]
Fixed in latest commit
